### ISSUE TITLE
Add Kibana + ElasticSearch + FluentBit logs

### ISSUE THREAD

**Issue by JMLX42** [democratech/2022#20]
- [x] Working Ansible role to setup an EFK (ElasticSearch + Fluent-bit + Kibana) stack.
- [x] Persistent data for ElasticSearch ~~and Kibana~~ (cf https://github.com/democratech/2022/issues/20#issuecomment-813676002).
- [x] Create a ~~dedicated democratech/infra team~~ list of GitHub users (cf https://github.com/democratech/2022/issues/20#issuecomment-813677591) that will be whitelisted by Vouch
- [x] Setup authentication for Kibana using Vouch
- [x] Disable auth by default on the local dev environment
- [x] Update the documentation.
- [x] Deploy
- [x] Confirm that https://logs.infra.laprimaire.org is accessible only after authenticating via GitHub
- [x] Confirm that Kibana works as expected to explore the logs

**Comment by JMLX42** [comment]
Apparently, the logging happens at the docker daemon level: https://github.com/docker/compose/issues/2657 So it's impossible to use a bridge network to communicate between fluent-bit and other apps.

One solution might be to add a fluent-bit container to each docker-compose stack and add them to a shared `elasticsearch` network.

**Comment by JMLX42** [comment]
Kibana requires the XPACK extension to enable the login form. And XPACK os not part of the OSS offer. So I'll use a Vouch reverse proxy instead:

https://github.com/vouch/vouch-proxy

**Comment by JMLX42** [comment]
> One solution might be to add a fluent-bit container to each docker-compose stack and add them to a shared `elasticsearch` network.

This worked:

```yml
fluent-bit:
    image: fluent/fluent-bit:1.7.2
    ports:
      - 24224:24224
      - 24224:24224/udp
```

For each service we want the logs from, in the relevant `docker-compose.yml` files:

```yml
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        fluentd-async: "true"
```
