### ISSUE TITLE
Fix "non secure connection on the server" warning on Matomo

### ISSUE THREAD

**Issue by JMLX42** [democratech/2022#33]
![image](https://user-images.githubusercontent.com/998703/113633972-31bd7180-966e-11eb-96a6-569bb5766172.png)

This warning is because the SSL is provided by the Nginx proxy + Let'sEncrypt + Cloudflare. So Matomo sees an `https` URL but actually runs HTTP on the 80 port. 

The solution is to add the line `assume_secure_protocol=1` below the `[General]` section in the Matomo configuration.

- [ ] Fix the Matomo configuration.

**Comment by JMLX42** [comment]
Sadly, there is no env var to set this directly from the `docker-compose.yml` file: https://github.com/bitnami/bitnami-docker-matomo/issues/71

**Comment by JMLX42** [comment]
Here is how to fix it:

```yml
- name: wait for config.ini.php to be written
  wait_for:
    path: /data/matomo/data/config/config.ini.php
    search_regex: '^\[General\]$'

- name: set "assume_secure_protocol = 1"
  lineinfile:
    path: /data/matomo/data/config/config.ini.php
    line: "assume_secure_protocol = 1"
    insertafter: '^\[General\]$'
    state: present
```

:point_up_2: this must be added at the end of the role's tasks.
